storage: binary
autosave: 300
version: 0
# Available variables in messages: {{sender}} {{target}} {{num}} {{time}} {{error}}. Will be empty if not found.
messages:
  prefix: "&a[PlayTime+] &r"
  cmd:
    playtime:
      error: "{{prefix}}&cERROR: {{error}}"
      other:
        success: "{{prefix}}&d{{target}} &ehas played for &d{{time}}§e."
        fail: "{{prefix}}Couldn't find player {{target}}"
      query:
        help: "{{prefix}}Go to this page for help: https://goo.gl/Y1KeoG"
        start: "{{prefix}}Performing query..."
        success: "{{prefix}}Query finished!"
        eachPlayer: "{{prefix}}&d{{target}} &e-> &d{{time}}"
        queryError: "{{prefix}}&cQuery Error: {{error}}"
      self:
        consoleuse: "{{prefix}}Only players can execute this command"
        success: "{{prefix}}&dYou &ehave played for &d{{time}}&e."
      top:
        header: "&e---------------&a[Playtime Top]&e---------------"
        eachPlayer: "&d#{{num}}. &r{{target}} &ewith &d{{time}}&e."