name: PlayTimePlus
author: Deanveloper
main: com.deanveloper.playtimeplus.PlayTimePlus
version: ${project.version}
softdepend: [GroupManager, Essentials]
commands:
  playtimeplus:
    permission: playtimeplus.command.playtimeplus
    description: "Checks the amount of time someone has played"
    aliases: [playtime, ptp]
  exportplayers:
    permission: playtimeplus.command.exportplayers
    description: "Exports players to a file"
    usage: "/exportplayers [help|filetype]"
  debug:
    permission: playtimeplus.command.debug
    description: "Enable debug mode"
    usage: "/debug [true|false]"

permissions:
  playtimeplus.command.playtimeplus:
    description: "Allows access to use /playtimeplus (Note: subcommands must be given separately)"
    default: true
  playtimeplus.command.playtimeplus.self:
    description: "Allows access to view their own play time"
    default: true
    children:
      playtime.command.playtimeplus: true
  playtimeplus.command.playtimeplus.top:
    description: "Allows access to view the top 10 players"
    default: true
    children:
      playtimeplus.command.playtimeplus: true
  playtimeplus.command.playtimeplus.other:
    description: "Allows access to view other people's playtimes"
    default: op
    children:
      playtime.command.playtimeplus: true
  playtimeplus.command.playtimeplus.*:
    description: "Allows full access to the /playtimeplus command"
    default: op
    children:
      playtimeplus.command.playtimeplus.self: true
      playtimeplus.command.playtimeplus.other: true
      playtimeplus.command.playtimeplus.change: true
      playtimeplus.command.playtimeplus.top: true
  playtimeplus.command.exportplayers:
    description: "Allows access to the /exportplayers command"
    default: op
  playtimeplus.podium:
    description: "Allows the creation/destruction of a podium"
    default: op
